name: wave_tracing
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - matplotlib>=3.1
  - numpy>=1.17
  - scipy>=1.2
  - netcdf4
  - xarray
  - pyproj>=2.3
  - cartopy
  - pip
  - yaml
  - ipython
  - cmocean
  - jupyterlab
  - pytest
